### ISSUE TITLE
Make errors more informative

### ISSUE THREAD

**Issue by Amomum** [rumkit/PixelPixie#19]
Right now most of the errors are like "Error parsing arguments. Check command line." or "Error parsing file" and user has no idea what argument was the cause or what file was not parsed correctly.

**Comment by Amomum** [comment]
I tried simply rethrowing exception instead of returning critical error code and it's MUCH more informative!

![image](https://user-images.githubusercontent.com/4990494/84896256-4d8a6380-b0ac-11ea-9cc8-2c0870ae45fe.png)

vs

```
Parsing bitmap to byte array


Unhandled Exception: Pixie.PixelProcessingException: Problem detected while processing pixel at 13,17 ---> Pixie.PixelProcessingException: Can't find corresponding bits to pixel color #FF0000. Check your config
   at Pixie.PixelMapper.ProcessPixel(Color color, Int32 bitsPerPixel, BitArray outputArray, Int32& outputArrayPosition) in H:\GitLocalRepos\PixelPixie\Pixie\PixelMapper.cs:line 117
   at Pixie.PixelMapper.ProcessSymbol(Int32 symbolXStart, Int32 symbolXEnd, Int32 symbolYStart, Int32 symbolYEnd) in H:\GitLocalRepos\PixelPixie\Pixie\PixelMapper.cs:line 96
   --- End of inner exception stack trace ---
   at Pixie.PixelMapper.ProcessSymbol(Int32 symbolXStart, Int32 symbolXEnd, Int32 symbolYStart, Int32 symbolYEnd) in H:\GitLocalRepos\PixelPixie\Pixie\PixelMapper.cs:line 100
   at Pixie.PixelMapper.MapPixels(Boolean skipHeaders) in H:\GitLocalRepos\PixelPixie\Pixie\PixelMapper.cs:line 63
   at Pixie.Program.ParseFontImage(ParseOptions options) in H:\GitLocalRepos\PixelPixie\Pixie\Program.cs:line 91
   at Pixie.Program.Main(String[] args) in H:\GitLocalRepos\PixelPixie\Pixie\Program.cs:line 22
```
Even a human-readable error message is already there.

**Comment by rumkit** [comment]
Probably should add verbosity key or smth like that to control such behavior

**Comment by roman-khazanskii** [comment]
Well, it's certainly _beta_ then just "critical error"; I guess just printing exception message would be a more "correct" way to do it but that will require more severe changes.

**Comment by Amomum** [comment]
Oops, wrong account :D 
Well, it's certainly beta then just "critical error"; I guess just printing exception message would be a more "correct" way to do it but that will require more severe changes.
